FROM golang:alpine

ENV GIN_MODE=release
ENV PORT=8080

WORKDIR /src

COPY cmd /src/cmd
COPY internal /src/internal
COPY go.mod /src
COPY go.sum /src

RUN apk add --no-cache ca-certificates && update-ca-certificates

RUN apk update && apk add --no-cache git
RUN go get ./...

RUN go build cmd/apiserver/main.go

EXPOSE $PORT

ENTRYPOINT ["./main"]