FROM golang:alpine


WORKDIR /src

COPY cmd /src/cmd
COPY internal /src/internal
COPY go.mod /src
COPY go.sum /src

RUN apk add --no-cache ca-certificates && update-ca-certificates

RUN apk update && apk add --no-cache git
RUN go get ./...

RUN go build cmd/daemon/loader/main.go

EXPOSE $PORT

ENTRYPOINT ["./main"]